---
- name: ensure dockutil installed
  community.general.homebrew:
    name: "dockutil"
    state: "latest"

- name: ensure clean dock
  shell:
    cmd: dockutil --remove all --no-restart

- name: ensure apps added to dock
  shell:
    cmd: dockutil --add "{{ item.path }}" --view "{{ item.view|default('grid') }}" --sort "{{ item.sort|default('name') }}" --no-restart
  with_items:
    - "{{ macos_dock_apps }}"

- name: restart dock
  shell:
    cmd: killall Dock
