---
- name: Ensure dockutil installed
  ansible.builtin.shell:
    cmd: dockutil --version
  register: result
  check_mode: false
  changed_when: false
  failed_when: result.rc != 0

- name: Ensure clean dock
  ansible.builtin.shell:
    cmd: dockutil --remove all --no-restart

- name: Ensure apps added to dock
  ansible.builtin.shell:
    cmd: dockutil --add "{{ item.path }}" --view "{{ item.view | default('grid') }}" --sort "{{ item.sort | default('name') }}" --no-restart
  with_items:
    - "{{ macos_dock_apps }}"

- name: Restart dock
  ansible.builtin.shell:
    cmd: killall Dock
